import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, ActivityIndicator } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { MaterialIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import { colors } from '../../src/theme/colors';
import { agentsApi } from '../../src/services/api/endpoints';

export default function BRSRScreen() {
  const insets = useSafeAreaInsets();
  const router = useRouter();

  const { data, isLoading, isError, refetch } = useQuery({
    queryKey: ['brsrReport'],
    queryFn: () => agentsApi.getLatestBRSR(),
  });

  const report = data?.data;

  return (
    <View style={styles.container}>
      <View style={[styles.header, { paddingTop: insets.top }]}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
          <MaterialIcons name="arrow-back" size={24} color={colors.textHeader} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>BRSR Scope 2 Report</Text>
      </View>

      {isLoading ? (
        <ActivityIndicator size="large" color={colors.primary} style={styles.loader} />
      ) : isError ? (
        <View style={styles.centerBox}>
          <Text style={styles.errorText}>Error loading BRSR report</Text>
          <TouchableOpacity onPress={() => refetch()}>
            <Text style={styles.retryText}>Retry</Text>
          </TouchableOpacity>
        </View>
      ) : !report ? (
        <View style={styles.centerBox}>
          <Text style={styles.errorText}>No BRSR report generated yet.</Text>
        </View>
      ) : (
        <ScrollView contentContainerStyle={styles.content}>
          <View style={styles.reportCard}>
            <View style={styles.reportHeader}>
              <MaterialIcons name="assessment" size={24} color={colors.primary} />
              <Text style={styles.reportTitle}>Annual BRSR Summary</Text>
            </View>
            <View style={styles.divider} />
            <Text style={styles.sectionTitle}>Scope 2 Emissions (Purchased Electricity)</Text>
            <View style={styles.statRow}>
              <Text style={styles.statLabel}>Total Compute Footprint:</Text>
              <Text style={styles.statValue}>{report.totalCo2Kg?.toFixed(2)} kg CO₂</Text>
            </View>
            <View style={styles.statRow}>
              <Text style={styles.statLabel}>Total Energy Consumed:</Text>
              <Text style={styles.statValue}>{report.totalEnergyKwh?.toFixed(2)} kWh</Text>
            </View>
            
            <View style={styles.divider} />
            <Text style={styles.sectionTitle}>Provider Breakdown</Text>
            {report.providerBreakdown && Object.entries(report.providerBreakdown).map(([provider, val]: any) => (
              <View key={provider} style={styles.statRow}>
                <Text style={styles.statLabel}>{provider.toUpperCase()}:</Text>
                <Text style={styles.statValue}>{val?.toFixed(2)} kg CO₂</Text>
              </View>
            ))}

            <View style={styles.divider} />
            <Text style={styles.sectionTitle}>Generated By</Text>
            <Text style={styles.metaText}>Reporter Agent (Auto-generated)</Text>
            <Text style={styles.metaText}>Date: {new Date(report.createdAt).toLocaleDateString()}</Text>
          </View>
        </ScrollView>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#141414' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 16,
    backgroundColor: '#1E1E1E',
    borderBottomWidth: 1,
    borderBottomColor: '#2A2A2A',
  },
  backBtn: { padding: 8, marginLeft: -8, marginRight: 8 },
  headerTitle: { fontFamily: 'Inter-Bold', fontSize: 20, color: colors.textHeader },
  loader: { marginTop: 40 },
  centerBox: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  errorText: { color: colors.textMuted, fontFamily: 'Inter', marginBottom: 12 },
  retryText: { color: colors.primary, fontFamily: 'Inter-Bold' },
  content: { padding: 20 },
  reportCard: {
    backgroundColor: '#1E1E1E',
    borderWidth: 1,
    borderColor: '#2A2A2A',
    borderRadius: 12,
    padding: 20,
  },
  reportHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 16 },
  reportTitle: { fontFamily: 'Inter-Bold', fontSize: 18, color: colors.textHeader },
  divider: { height: 1, backgroundColor: '#2A2A2A', marginVertical: 16 },
  sectionTitle: { fontFamily: 'JetBrainsMono-Bold', fontSize: 12, color: colors.primary, marginBottom: 12, textTransform: 'uppercase' },
  statRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  statLabel: { fontFamily: 'Inter', fontSize: 14, color: colors.textMuted },
  statValue: { fontFamily: 'JetBrains Mono', fontSize: 14, color: colors.textHeader },
  metaText: { fontFamily: 'JetBrains Mono', fontSize: 12, color: colors.textMuted, marginTop: 4 },
});
