#!/usr/bin/env node
/**
 * CarboniX SDK — postinstall init script
 *
 * Runs automatically on `npm install carbonix`.
 * Does 3 things with ZERO manual work from the developer:
 *
 *  1. Creates  carbonix.config.js      — SDK config (API key, base URL)
 *  2. Creates  carbonix-telemetry.js   — Background CPU reporter
 *  3. AUTO-INJECTS startTelemetry()   — Finds their entry file and appends 8 lines
 */

const fs   = require('fs');
const path = require('path');
const os   = require('os');

// ─── Resolve the consumer project root ───────────────────────────────────────
// npm sets INIT_CWD to the directory where `npm install` was run.
function findProjectRoot() {
  if (process.env.INIT_CWD) return process.env.INIT_CWD;
  return path.resolve(__dirname, '../../..');
}

const projectRoot = findProjectRoot();

// ─── 1. Auto-detect entry file ────────────────────────────────────────────────
const CANDIDATE_ENTRY_FILES = [
  'server.js', 'server.ts',
  'index.js',  'index.ts',
  'app.js',    'app.ts',
  'src/server.js', 'src/server.ts',
  'src/index.js',  'src/index.ts',
  'src/app.js',    'src/app.ts',
  'main.js',   'main.ts',
];

function detectEntryFile() {
  // First: check "main" in the user's package.json
  const pkgPath = path.join(projectRoot, 'package.json');
  if (fs.existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
      if (pkg.main) {
        const mainFile = path.join(projectRoot, pkg.main);
        if (fs.existsSync(mainFile)) return pkg.main;
      }
    } catch (_) {}
  }
  // Second: walk the candidate list
  for (const c of CANDIDATE_ENTRY_FILES) {
    if (fs.existsSync(path.join(projectRoot, c))) return c;
  }
  return null;
}

// ─── 2. Auto-detect cloud config from .env ────────────────────────────────────
function detectConfig() {
  const envVars = {};
  const envPath = path.join(projectRoot, '.env');
  if (fs.existsSync(envPath)) {
    fs.readFileSync(envPath, 'utf8').split('\n').forEach(line => {
      const m = line.match(/^([^#=]+)=(.*)$/);
      if (m) envVars[m[1].trim()] = m[2].trim().replace(/^["']|["']$/g, '');
    });
  }
  return {
    instanceId:   envVars.INSTANCE_ID    || os.hostname(),
    instanceType: envVars.INSTANCE_TYPE  || 't3.medium',
    provider:     (envVars.CLOUD_PROVIDER || 'aws').toLowerCase(),
    region:       envVars.AWS_REGION || envVars.GCP_REGION || envVars.AZURE_REGION || 'ap-south-1',
    projectName:  envVars.APP_NAME  || envVars.SERVICE_NAME || path.basename(projectRoot),
  };
}

// ─── 3. Injection snippet ─────────────────────────────────────────────────────
function buildSnippet(cfg) {
  return [
    '',
    '// ─── CarboniX Auto-injected (do not remove) ───────────────────────────────',
    "const { startTelemetry } = require('./carbonix-telemetry');",
    'startTelemetry({',
    `  instanceId:   process.env.INSTANCE_ID    || '${cfg.instanceId}',`,
    `  instanceType: process.env.INSTANCE_TYPE  || '${cfg.instanceType}',`,
    `  provider:     process.env.CLOUD_PROVIDER || '${cfg.provider}',`,
    `  region:       process.env.AWS_REGION     || '${cfg.region}',`,
    `  projectName:  process.env.APP_NAME       || '${cfg.projectName}',`,
    '});',
    '// ───────────────────────────────────────────────────────────────────────────',
    '',
  ].join('\n');
}

// ─── File templates ───────────────────────────────────────────────────────────

const CONFIG_CONTENT = `/**
 * CarboniX Configuration — generated by \`npm install carbonix\`
 * Set CARBONIX_API_KEY in your .env file.
 * Get your API key from your CarboniX Dashboard.
 */
const Carbonix = require('carbonix').default;

const cx = new Carbonix({
  apiKey:  process.env.CARBONIX_API_KEY  || 'cx_YOUR_API_KEY_HERE',
  baseUrl: process.env.CARBONIX_BASE_URL || 'http://localhost:4000',
  timeoutMs: 10_000,
});

module.exports = { cx };
`;

const TELEMETRY_CONTENT = `/**
 * CarboniX Telemetry Reporter — generated by \`npm install carbonix\`
 * Pushes live CPU metrics to your CarboniX Dashboard every 5 minutes.
 * The AI Analyst flags idle/oversized instances and suggests savings.
 */
const os = require('os');
const { cx } = require('./carbonix.config');

function getCpuUtilization() {
  return new Promise(resolve => {
    const t1 = os.cpus();
    setTimeout(() => {
      const t2 = os.cpus();
      let idle = 0, total = 0;
      t1.forEach((cpu, i) => {
        for (const type in t2[i].times) total += t2[i].times[type] - cpu.times[type];
        idle += t2[i].times.idle - cpu.times.idle;
      });
      resolve(parseFloat((1 - idle / total).toFixed(4)));
    }, 100);
  });
}

function startTelemetry({ instanceId, instanceType, provider, region, projectName, intervalMs = 5 * 60 * 1000, storageGb = 0 }) {
  if (!instanceId || !instanceType || !provider || !region) {
    console.warn('[CarboniX] startTelemetry() missing required fields.');
    return;
  }
  const report = async () => {
    try {
      const cpuUtilization = await getCpuUtilization();
      const record = await cx.ingest({ instanceId, instanceType, provider, region, cpuUtilization, storageGb, projectName });
      console.log(\`[CarboniX] 📊 \${record.carbonKg.toFixed(4)} kg CO₂ | CPU: \${(cpuUtilization * 100).toFixed(1)}% | idle: \${record.isIdle}\`);
    } catch (err) {
      console.warn('[CarboniX] Telemetry failed (non-fatal):', err.message);
    }
  };
  report();
  const timer = setInterval(report, intervalMs);
  if (timer.unref) timer.unref();
  console.log(\`[CarboniX] ✅ Reporting every \${intervalMs / 1000}s for \${instanceId}\`);
  return { stop: () => clearInterval(timer) };
}

module.exports = { startTelemetry };
`;

// ─── Execute ─────────────────────────────────────────────────────────────────

console.log('');
console.log('🌿 CarboniX SDK — setting up your project...');
console.log('');

const configPath    = path.join(projectRoot, 'carbonix.config.js');
const telemetryPath = path.join(projectRoot, 'carbonix-telemetry.js');

// Step 1: Scaffold config
if (!fs.existsSync(configPath)) {
  fs.writeFileSync(configPath, CONFIG_CONTENT, 'utf8');
  console.log('  ✅  Created  carbonix.config.js');
} else {
  console.log('  ⏭️   Skipped  carbonix.config.js (already exists)');
}

// Step 2: Scaffold telemetry reporter
if (!fs.existsSync(telemetryPath)) {
  fs.writeFileSync(telemetryPath, TELEMETRY_CONTENT, 'utf8');
  console.log('  ✅  Created  carbonix-telemetry.js');
} else {
  console.log('  ⏭️   Skipped  carbonix-telemetry.js (already exists)');
}

// Step 3: Auto-inject startTelemetry() into entry file
const entryFile = detectEntryFile();
const config    = detectConfig();
const MARKER    = 'CarboniX Auto-injected';

if (entryFile) {
  const entryPath    = path.join(projectRoot, entryFile);
  const entryContent = fs.readFileSync(entryPath, 'utf8');

  if (entryContent.includes(MARKER)) {
    console.log(`  ⏭️   Skipped  auto-inject (already in ${entryFile})`);
  } else {
    fs.appendFileSync(entryPath, buildSnippet(config), 'utf8');
    console.log(`  ✅  Injected  startTelemetry() → ${entryFile}`);
    console.log(`              instanceId:   ${config.instanceId}`);
    console.log(`              instanceType: ${config.instanceType}`);
    console.log(`              provider:     ${config.provider} / ${config.region}`);
  }
} else {
  console.log('  ⚠️   Entry file not found — add this to your server.js manually:');
  console.log("       const { startTelemetry } = require('./carbonix-telemetry');");
  console.log("       startTelemetry({ instanceId: 'my-server', instanceType: 't3.medium', provider: 'aws', region: 'ap-south-1' });");
}

// Step 4: Banner
console.log('');
console.log('╔══════════════════════════════════════════════════════════╗');
console.log('║        🌿  CarboniX SDK installed successfully!          ║');
console.log('╠══════════════════════════════════════════════════════════╣');
console.log('║  ✅  carbonix.config.js         (SDK config)            ║');
console.log('║  ✅  carbonix-telemetry.js      (live CPU reporter)     ║');
console.log('║  ✅  startTelemetry() injected  (auto-detected)         ║');
console.log('║                                                          ║');
console.log('║  👉 Only one step left:                                  ║');
console.log('║     Add to your .env:                                    ║');
console.log('║     CARBONIX_API_KEY=cx_your_key_here                   ║');
console.log('║                                                          ║');
console.log('║     Get your key at → app.carbonix.dev                  ║');
console.log('║                                                          ║');
console.log('║  Your Dashboard shows live data on next server start 🚀 ║');
console.log('╚══════════════════════════════════════════════════════════╝');
console.log('');
