#!/usr/bin/env node

import { Command } from 'commander';
import pc from 'picocolors';
import axios from 'axios';
import fs from 'fs/promises';
import path from 'path';
import os from 'os';

const program = new Command();
const CONFIG_PATH = path.join(process.cwd(), '.carbonixrc');

// ─── Use CARBONIX_API_URL env var, then .carbonixrc baseUrl, then default ────
const DEFAULT_API_BASE = process.env.CARBONIX_API_URL || 'https://api-production-f6965.up.railway.app';

// ─── Brand Banner ─────────────────────────────────────────────────────────────
function printBanner() {
  console.log('');
  console.log(pc.yellow('   ██████╗ ██╗  ██╗'));
  console.log(pc.yellow('  ██╔════╝ ╚██╗██╔╝'));
  console.log(pc.yellow('  ██║       ╚███╔╝ '));
  console.log(pc.yellow('  ██║       ██╔██╗ '));
  console.log(pc.yellow('  ╚██████╗ ██╔╝ ██╗'));
  console.log(pc.yellow('   ╚═════╝ ╚═╝  ╚═╝') + pc.green('  CarboniX CLI'));
  console.log('');
}

// ─── Templates ───────────────────────────────────────────────────────────────

const CONFIG_JS_CONTENT = (apiKey: string, baseUrl: string) => `/**
 * CarboniX Configuration
 * Generated by: npx @carbonix/cli init
 * ─────────────────────────────────────────────────────────────────────────────
 * Set CARBONIX_API_KEY in your .env to override the key below.
 * Get your key from your CarboniX Dashboard → Settings → API Keys
 */
const Carbonix = require('carbonix').default;

const cx = new Carbonix({
  apiKey:  process.env.CARBONIX_API_KEY  || '${apiKey}',
  baseUrl: process.env.CARBONIX_BASE_URL || '${baseUrl}',
  timeoutMs: 10_000,
});

module.exports = { cx };
`;

const TELEMETRY_JS_CONTENT = `/**
 * CarboniX Telemetry Reporter
 * Generated by: npx @carbonix/cli init
 * ─────────────────────────────────────────────────────────────────────────────
 * Reports live CPU metrics to your CarboniX Dashboard every 5 minutes.
 * The AI Analyst flags idle/oversized instances and suggests savings.
 */
const os = require('os');
const { cx } = require('./carbonix.config');

function getCpuUtilization() {
  return new Promise(resolve => {
    const t1 = os.cpus();
    setTimeout(() => {
      const t2 = os.cpus();
      let idle = 0, total = 0;
      t1.forEach((cpu, i) => {
        for (const type in t2[i].times) total += t2[i].times[type] - cpu.times[type];
        idle += t2[i].times.idle - cpu.times.idle;
      });
      resolve(parseFloat((1 - idle / total).toFixed(4)));
    }, 100);
  });
}

function startTelemetry({ instanceId, instanceType, provider, region, projectName, intervalMs = 5 * 60 * 1000, storageGb = 0 }) {
  const report = async () => {
    try {
      const cpuUtilization = await getCpuUtilization();
      const record = await cx.ingest({ instanceId, instanceType, provider, region, cpuUtilization, storageGb, projectName });
      console.log(\`[CarboniX] 📊 \${record.carbonKg.toFixed(4)} kg CO₂ | CPU: \${(cpuUtilization * 100).toFixed(1)}% | idle: \${record.isIdle}\`);
    } catch (err) {
      console.warn('[CarboniX] Telemetry failed (non-fatal):', err.message);
    }
  };
  report();
  const timer = setInterval(report, intervalMs);
  if (timer.unref) timer.unref();
  console.log(\`[CarboniX] ✅ Reporting every \${intervalMs / 1000}s for \${instanceId}\`);
  return { stop: () => clearInterval(timer) };
}

module.exports = { startTelemetry };
`;

// ─── Helpers ──────────────────────────────────────────────────────────────────

const ENTRY_FILE_CANDIDATES = [
  'server.js', 'server.ts', 'index.js', 'index.ts', 'app.js', 'app.ts',
  'src/server.js', 'src/server.ts', 'src/index.js', 'src/index.ts',
  'src/app.js', 'src/app.ts', 'main.js', 'main.ts',
];

async function detectEntryFile(cwd: string): Promise<string | null> {
  try {
    const pkg = JSON.parse(await fs.readFile(path.join(cwd, 'package.json'), 'utf-8'));
    if (pkg.main && await fileExists(path.join(cwd, pkg.main))) return pkg.main;
  } catch (_) {}
  for (const c of ENTRY_FILE_CANDIDATES) {
    if (await fileExists(path.join(cwd, c))) return c;
  }
  return null;
}

async function fileExists(p: string): Promise<boolean> {
  try { await fs.access(p); return true; } catch { return false; }
}

async function detectEnvVars(cwd: string): Promise<Record<string, string>> {
  const vars: Record<string, string> = {};
  for (const envFile of ['.env', '.env.local', '.env.production']) {
    try {
      const lines = (await fs.readFile(path.join(cwd, envFile), 'utf-8')).split('\n');
      for (const line of lines) {
        const m = line.match(/^([^#=]+)=(.*)$/);
        if (m) vars[m[1].trim()] = m[2].trim().replace(/^["']|["']$/g, '');
      }
    } catch (_) {}
  }
  return vars;
}

async function readConfig(): Promise<any> {
  try {
    const data = await fs.readFile(CONFIG_PATH, 'utf-8');
    return JSON.parse(data);
  } catch {
    console.error(pc.red('\n  ❌  Not initialized. Run:') + pc.white('  npx @carbonix/cli init --key <your-api-key>\n'));
    process.exit(1);
  }
}

function detectProvider(envVars: Record<string, string>): string {
  if (process.env.VERCEL               || envVars.VERCEL)               return 'vercel';
  if (process.env.NETLIFY              || envVars.NETLIFY)               return 'netlify';
  if (process.env.RAILWAY_ENVIRONMENT  || envVars.RAILWAY_ENVIRONMENT)   return 'railway';
  if (process.env.RENDER               || envVars.RENDER)                return 'render';
  if (process.env.GOOGLE_CLOUD_PROJECT || envVars.GOOGLE_CLOUD_PROJECT)  return 'gcp';
  if (process.env.ARM_REGION           || envVars.ARM_REGION || process.env.AZURE_REGION || envVars.AZURE_REGION) return 'azure';
  return 'aws';
}

function buildInjectionSnippet(cfg: Record<string, string>): string {
  return [
    '',
    '// ─── CarboniX Auto-injected by @carbonix/cli (do not remove) ──────────────',
    "const { startTelemetry } = require('./carbonix-telemetry');",
    'startTelemetry({',
    `  instanceId:   process.env.INSTANCE_ID    || '${cfg.instanceId}',`,
    `  instanceType: process.env.INSTANCE_TYPE  || '${cfg.instanceType}',`,
    `  provider:     process.env.CLOUD_PROVIDER || '${cfg.provider}',`,
    `  region:       process.env.AWS_REGION     || '${cfg.region}',`,
    `  projectName:  process.env.APP_NAME       || '${cfg.projectName}',`,
    '});',
    '// ───────────────────────────────────────────────────────────────────────────',
    '',
  ].join('\n');
}

// ─── CLI Setup ────────────────────────────────────────────────────────────────

program
  .name('carbonix')
  .description(pc.green('CarboniX') + ' — Carbon intelligence for your cloud infrastructure')
  .version('0.2.0')
  .addHelpText('before', pc.yellow('\n🌿 CarboniX CLI — Track & cut cloud carbon emissions\n'));

// ─── init ─────────────────────────────────────────────────────────────────────

program
  .command('init')
  .description('Initialize CarboniX in your project — scaffolds config, telemetry reporter, and auto-injects tracking')
  .requiredOption('-k, --key <key>', 'Your CarboniX API key (get it from your Dashboard → Settings → API Keys)')
  .option('--base-url <url>', 'Override the CarboniX API base URL', DEFAULT_API_BASE)
  .option('--skip-inject', 'Skip auto-injecting telemetry into your entry file')
  .action(async (options) => {
    printBanner();
    const cwd     = process.cwd();
    const apiKey  = options.key;
    const baseUrl = options.baseUrl;

    console.log(pc.cyan('  Initializing CarboniX in your project...'));
    console.log('');

    // ── Step 1: Verify the API key ────────────────────────────────────────────
    process.stdout.write(pc.gray('  [1/5] Verifying API key... '));
    try {
      const res = await axios.post(`${baseUrl}/api/v1/carbon/verify-key`, {}, {
        headers: { 'Authorization': `Bearer ${apiKey}` },
        timeout: 8000,
      });
      if (!res.data.success) throw new Error('Key invalid');
      console.log(pc.green('✅ Valid'));
    } catch (err: any) {
      if (err.code === 'ECONNREFUSED' || err.code === 'ENOTFOUND') {
        console.log(pc.red('❌ Cannot reach server'));
        console.error(pc.red(`\n  Cannot connect to: ${baseUrl}`));
        console.error(pc.gray('  Make sure your CarboniX server is running or set --base-url to your deployed API.'));
      } else {
        console.log(pc.red('❌ Invalid key'));
        console.error(pc.red(`\n  Error: ${err.response?.data?.error || err.message}`));
        console.error(pc.gray('  Get your API key from: Dashboard → Settings → API Keys'));
      }
      process.exit(1);
    }

    // ── Step 2: Auto-detect environment ───────────────────────────────────────
    process.stdout.write(pc.gray('  [2/5] Detecting environment... '));
    const envVars = await detectEnvVars(cwd);
    const provider = detectProvider(envVars);
    const region = envVars.AWS_REGION || envVars.GCP_REGION || envVars.AZURE_REGION || process.env.AWS_REGION || 'ap-south-1';
    const instanceId = envVars.INSTANCE_ID || os.hostname();
    const instanceType = envVars.INSTANCE_TYPE || 't3.medium';
    const projectName = envVars.APP_NAME || (() => {
      try { return require(path.join(cwd, 'package.json')).name; } catch { return path.basename(cwd); }
    })();
    console.log(pc.green(`✅ ${provider.toUpperCase()} / ${region}`));

    const cfg = { instanceId, instanceType, provider, region, projectName };

    // ── Step 3: Write .carbonixrc ──────────────────────────────────────────────
    process.stdout.write(pc.gray('  [3/5] Writing .carbonixrc... '));
    const rcPath = path.join(cwd, '.carbonixrc');
    await fs.writeFile(rcPath, JSON.stringify({ apiKey, provider, region, baseUrl, projectName }, null, 2));
    console.log(pc.green('✅ Done'));

    // ── Step 4: Write config + telemetry files ─────────────────────────────────
    process.stdout.write(pc.gray('  [4/5] Scaffolding config files... '));
    const configPath = path.join(cwd, 'carbonix.config.js');
    if (!(await fileExists(configPath))) {
      await fs.writeFile(configPath, CONFIG_JS_CONTENT(apiKey, baseUrl));
    }
    const telemetryPath = path.join(cwd, 'carbonix-telemetry.js');
    if (!(await fileExists(telemetryPath))) {
      await fs.writeFile(telemetryPath, TELEMETRY_JS_CONTENT);
    }
    console.log(pc.green('✅ Done'));

    // ── Step 5: Auto-inject into entry file ────────────────────────────────────
    process.stdout.write(pc.gray('  [5/5] Injecting telemetry hook... '));
    if (options.skipInject) {
      console.log(pc.gray('skipped (--skip-inject)'));
    } else {
      const entryFile = await detectEntryFile(cwd);
      const MARKER = 'CarboniX Auto-injected';
      if (entryFile) {
        const entryContent = await fs.readFile(path.join(cwd, entryFile), 'utf-8');
        if (entryContent.includes(MARKER)) {
          console.log(pc.gray(`already injected`));
        } else {
          await fs.appendFile(path.join(cwd, entryFile), buildInjectionSnippet(cfg));
          console.log(pc.green(`✅ → ${entryFile}`));
        }
      } else {
        console.log(pc.yellow('⚠️  entry file not found — inject manually'));
      }
    }

    // ── Success Banner ────────────────────────────────────────────────────────
    console.log('');
    console.log(pc.green('  ┌─────────────────────────────────────────────────────┐'));
    console.log(pc.green('  │') + pc.bold('  🌿 CarboniX initialized successfully!              ') + pc.green('│'));
    console.log(pc.green('  ├─────────────────────────────────────────────────────┤'));
    console.log(pc.green('  │') + `  Provider : ${pc.cyan(provider.padEnd(10))} Region : ${pc.cyan(region.padEnd(16))}` + pc.green('  │'));
    console.log(pc.green('  │') + `  Project  : ${pc.white(projectName.substring(0, 37).padEnd(39))}` + pc.green('│'));
    console.log(pc.green('  ├─────────────────────────────────────────────────────┤'));
    console.log(pc.green('  │') + pc.gray('  ✅  .carbonixrc                                     ') + pc.green('│'));
    console.log(pc.green('  │') + pc.gray('  ✅  carbonix.config.js                              ') + pc.green('│'));
    console.log(pc.green('  │') + pc.gray('  ✅  carbonix-telemetry.js                           ') + pc.green('│'));
    console.log(pc.green('  ├─────────────────────────────────────────────────────┤'));
    console.log(pc.green('  │') + pc.white('  Next steps:                                        ') + pc.green('│'));
    console.log(pc.green('  │') + pc.gray('  › Start your server — live data flows to Dashboard ') + pc.green('│'));
    console.log(pc.green('  │') + pc.gray('  › carbonix status   — check live connection         ') + pc.green('│'));
    console.log(pc.green('  │') + pc.gray('  › carbonix app analyze — AI region optimizer        ') + pc.green('│'));
    console.log(pc.green('  └─────────────────────────────────────────────────────┘'));
    console.log('');
  });

// ─── status ───────────────────────────────────────────────────────────────────

program
  .command('status')
  .description('Check your CarboniX connection and show live emission stats')
  .action(async () => {
    const config = await readConfig();
    const baseUrl = config.baseUrl || DEFAULT_API_BASE;

    console.log('');
    console.log(pc.cyan('  🔍 Checking CarboniX connection...'));
    console.log('');

    // Ping server
    try {
      process.stdout.write(pc.gray('  API Server... '));
      await axios.get(`${baseUrl}/api/v1/health`, { timeout: 5000 });
      console.log(pc.green('✅ Online'));
    } catch {
      console.log(pc.red('❌ Offline'));
      console.error(pc.gray(`  Cannot reach: ${baseUrl}`));
      process.exit(1);
    }

    // Verify key
    try {
      process.stdout.write(pc.gray('  API Key...    '));
      const res = await axios.post(`${baseUrl}/api/v1/carbon/verify-key`, {}, {
        headers: { 'Authorization': `Bearer ${config.apiKey}` },
        timeout: 5000,
      });
      if (!res.data.success) throw new Error('invalid');
      console.log(pc.green('✅ Valid'));
    } catch {
      console.log(pc.red('❌ Invalid or expired'));
      console.error(pc.gray('  Get a new key from your Dashboard → Settings → API Keys'));
      process.exit(1);
    }

    // Fetch recent emission data
    try {
      process.stdout.write(pc.gray('  Emission data... '));
      const res = await axios.get(`${baseUrl}/api/v1/carbon/summary`, {
        headers: { 'Authorization': `Bearer ${config.apiKey}` },
        timeout: 5000,
      });
      console.log(pc.green('✅ Connected'));
      if (res.data?.data) {
        const d = res.data.data;
        console.log('');
        console.log(pc.white(`  Current Month  : ${pc.yellow(d.totalCarbonKg?.toFixed(2) + ' kg CO₂e')}`));
        console.log(pc.white(`  Instances      : ${pc.cyan(d.instanceCount)}`));
        console.log(pc.white(`  Idle Servers   : ${pc.red(d.idleCount)}`));
        console.log(pc.white(`  Oversized      : ${pc.red(d.oversizedCount)}`));
      }
    } catch {
      console.log(pc.gray('(no data yet — deploy and run your server to see emissions)'));
    }

    console.log('');
    console.log(pc.gray(`  Project  : ${config.projectName || 'unknown'}`));
    console.log(pc.gray(`  Provider : ${config.provider || 'unknown'} / ${config.region || 'unknown'}`));
    console.log(pc.gray(`  API Base : ${baseUrl}`));
    console.log('');
  });

// ─── auth login ───────────────────────────────────────────────────────────────

const authCmd = program.command('auth').description('Authentication commands');
authCmd
  .command('login')
  .description('Open your CarboniX Dashboard to get an API key')
  .action(() => {
    console.log('');
    console.log(pc.cyan('  To authenticate with CarboniX:'));
    console.log('');
    console.log(pc.white('  1. Open your Dashboard'));
    console.log(pc.gray('     https://carbonix.dev/admin/settings'));
    console.log('');
    console.log(pc.white('  2. Go to Settings → API Keys → Generate New Key'));
    console.log('');
    console.log(pc.white('  3. Run:'));
    console.log(pc.yellow('     npx @carbonix/cli init --key <your-api-key>'));
    console.log('');
  });

// ─── app analyze ──────────────────────────────────────────────────────────────

const appCmd = program.command('app').description('App management commands');

appCmd
  .command('analyze')
  .description('Analyze your deployment and get AI-powered region recommendations to cut carbon')
  .option('-p, --project <project>', 'Target project name')
  .action(async (options) => {
    const config = await readConfig();
    const baseUrl = config.baseUrl || DEFAULT_API_BASE;

    console.log('');
    console.log(pc.cyan('  🤖 CarboniX Agentic AI — Analyzing Environment...'));
    console.log('');

    const currentRegion   = config.region   || 'us-east-1';
    const currentProvider = config.provider || 'aws';

    const baseTelemetry = {
      projectName: options.project || config.projectName || 'local-analysis',
      instanceType: 't3.medium',
      provider: currentProvider,
      region: currentRegion,
      cpuUtilization: 0.2,
      storageGb: 20,
    };

    try {
      const recRes = await axios.post(`${baseUrl}/api/v1/carbon/recommend`, baseTelemetry, {
        headers: { 'Authorization': `Bearer ${config.apiKey}`, 'Content-Type': 'application/json' },
        timeout: 10000,
      });

      if (recRes.data.success) {
        if (recRes.data.data.recommended) {
          const rec = recRes.data.data.recommended;
          const currentCarbon = (rec.co2KgMonth + rec.savingsKg).toFixed(2);
          console.log(pc.yellow(`  ⚠️  Optimization Found!`));
          console.log('');
          console.log(`  Current : ${pc.white(currentProvider.toUpperCase())} ${pc.gray(currentRegion)}`);
          console.log(`  Carbon  : ${pc.red(currentCarbon + ' kg CO₂e/month')}`);
          console.log('');
          console.log(`  Optimal : ${pc.green(currentProvider.toUpperCase())} ${pc.green(rec.region)}`);
          console.log(`  Carbon  : ${pc.green(rec.co2KgMonth.toFixed(2) + ' kg CO₂e/month')}`);
          console.log('');
          console.log(pc.cyan(`  ✨ Savings: ~${Math.round(rec.reductionPercent)}% reduction (${rec.savingsKg.toFixed(2)} kg/month)`));
          console.log('');
          console.log(pc.gray('  Run `carbonix app deploy` to let the AI apply this automatically.'));
        } else {
          console.log(pc.green('  ✅ Your environment is already fully optimized!'));
          console.log(pc.gray(`  Running in the greenest available region: ${currentRegion}`));
        }
      }
    } catch (e: any) {
      console.error(pc.red(`  Error: ${e.response?.data?.error || e.message}`));
    }
    console.log('');
  });

// ─── app deploy ───────────────────────────────────────────────────────────────

appCmd
  .command('deploy')
  .description('Deploy and send telemetry to CarboniX with AI-powered carbon optimization')
  .option('-p, --project <project>', 'Target project name')
  .action(async (options) => {
    const config = await readConfig();
    const baseUrl = config.baseUrl || DEFAULT_API_BASE;

    let projectName = options.project || config.projectName;
    if (!projectName) {
      try {
        const pkgData = await fs.readFile(path.join(process.cwd(), 'package.json'), 'utf-8');
        projectName = JSON.parse(pkgData).name;
      } catch {
        projectName = 'unknown-project';
      }
    }

    console.log('');
    console.log(pc.cyan(`  📦 Deploying: ${projectName}`));
    console.log('');

    let currentRegion   = config.region   || 'us-east-1';
    let currentProvider = config.provider || 'aws';

    const baseTelemetry: any = {
      projectName,
      instanceType: 't3.medium',
      provider: currentProvider,
      region: currentRegion,
      cpuUtilization: Math.random() * 0.4 + 0.1,
      storageGb: 20,
    };

    // AI region optimization
    process.stdout.write(pc.gray('  [1/2] AI region optimization... '));
    try {
      const recRes = await axios.post(`${baseUrl}/api/v1/carbon/recommend`, baseTelemetry, {
        headers: { 'Authorization': `Bearer ${config.apiKey}`, 'Content-Type': 'application/json' },
        timeout: 10000,
      });

      if (recRes.data.success && recRes.data.data.recommended) {
        const rec = recRes.data.data.recommended;
        if (rec.reductionPercent > 10 && rec.region !== currentRegion) {
          console.log(pc.green(`switching region`));
          console.log(pc.green(`     ${currentRegion} → ${rec.region} (~${Math.round(rec.reductionPercent)}% less carbon)`));
          currentRegion = rec.region;
          baseTelemetry.region = currentRegion;

          // Rewrite vercel.json if present
          if (currentProvider.toLowerCase() === 'vercel') {
            try {
              const vercelConfigPath = path.join(process.cwd(), 'vercel.json');
              const vercelData = await fs.readFile(vercelConfigPath, 'utf-8');
              const vercelJson = JSON.parse(vercelData);
              if (vercelJson.regions && Array.isArray(vercelJson.regions)) {
                vercelJson.regions = [rec.region];
                await fs.writeFile(vercelConfigPath, JSON.stringify(vercelJson, null, 2));
                console.log(pc.yellow(`     📝 Updated vercel.json → region: ${rec.region}`));
              }
            } catch (_) {}
          }
        } else {
          console.log(pc.green('already optimal'));
        }
      } else {
        console.log(pc.gray('skipped'));
      }
    } catch {
      console.log(pc.gray('unavailable — using default region'));
    }

    // Send telemetry
    process.stdout.write(pc.gray('  [2/2] Uploading telemetry... '));
    try {
      const res = await axios.post(`${baseUrl}/api/v1/carbon/telemetry/ingest`, baseTelemetry, {
        headers: { 'Authorization': `Bearer ${config.apiKey}`, 'Content-Type': 'application/json' },
        timeout: 10000,
      });
      if (res.data.success) {
        console.log(pc.green('✅ Done'));
        console.log('');
        console.log(pc.green(`  🚀 Deployment recorded!`));
        console.log(pc.gray(`  Carbon: ${res.data.data?.carbonKg?.toFixed(4)} kg CO₂e`));
        console.log(pc.gray(`  Region: ${currentRegion} | Provider: ${currentProvider.toUpperCase()}`));
      } else {
        console.log(pc.red('❌ Failed'));
      }
    } catch (err: any) {
      console.log(pc.red('❌ Error'));
      console.error(pc.red(`  ${err.response?.data?.error || err.message}`));
    }
    console.log('');
  });

// ─── team sync ────────────────────────────────────────────────────────────────

const teamCmd = program.command('team').description('Team management commands');

teamCmd
  .command('sync')
  .description('Discover git contributors and sync them to your CarboniX Dashboard')
  .action(async () => {
    const config = await readConfig();
    const baseUrl = config.baseUrl || DEFAULT_API_BASE;

    let projectName = config.projectName || 'unknown-project';
    try {
      const pkgData = await fs.readFile(path.join(process.cwd(), 'package.json'), 'utf-8');
      projectName = JSON.parse(pkgData).name;
    } catch (_) {}

    console.log('');
    console.log(pc.cyan('  🔍 Scanning git history for contributors...'));

    const { execSync } = require('child_process');
    let gitOutput = '';
    try {
      gitOutput = execSync('git log --format="%an|%ae" | sort -u', { encoding: 'utf-8' });
    } catch {
      console.error(pc.yellow('  ⚠️  Not a git repo or git not installed.'));
      process.exit(0);
    }

    const members = gitOutput
      .split('\n')
      .filter((l: string) => l.trim())
      .map((line: string) => {
        const [name, email] = line.split('|');
        return { name: name?.trim(), email: email?.trim() };
      })
      .filter((m: any) => {
        const email = m.email?.toLowerCase() || '';
        return m.name && email && !email.includes('dependabot') && !email.includes('bot@') && !email.includes('noreply');
      });

    if (members.length === 0) {
      console.log(pc.yellow('  No human contributors found.'));
      return;
    }

    console.log(pc.gray(`  Found ${members.length} contributor(s). Syncing...`));

    try {
      const res = await axios.post(`${baseUrl}/api/v1/admin/users/sync`, { members, projectName }, {
        headers: { 'Authorization': `Bearer ${config.apiKey}`, 'Content-Type': 'application/json' },
        timeout: 10000,
      });
      if (res.data.success) {
        console.log(pc.green(`  ✅ Synced ${res.data.count} team member(s)!`));
        console.log(pc.gray('  View their emission ratings on your Dashboard → Team Emissions.'));
      } else {
        console.error(pc.red('  Sync failed.'));
      }
    } catch (err: any) {
      console.error(pc.red(`  Error: ${err.response?.data?.error || err.message}`));
    }
    console.log('');
  });

// ─── Parse ────────────────────────────────────────────────────────────────────

program.parse(process.argv);

if (!process.argv.slice(2).length) {
  printBanner();
  program.outputHelp();
}
