#!/usr/bin/env node

import { Command } from 'commander';
import pc from 'picocolors';
import axios from 'axios';
import fs from 'fs/promises';
import path from 'path';

const program = new Command();
const CONFIG_PATH = path.join(process.cwd(), '.carbonixrc');
const API_URL = process.env.CARBONIX_API_URL || 'http://localhost:4000/api/v1';

program
  .name('carbonix')
  .description('CarboniX Command Line Interface')
  .version('0.1.0');

// ─── Templates ───────────────────────────────────────────────────────────────

const CONFIG_JS_CONTENT = (apiKey: string, baseUrl: string) => `/**
 * CarboniX Configuration
 * Generated by: npx @carbonix/cli init
 * ─────────────────────────────────────────────────────────────────────────────
 * Set CARBONIX_API_KEY in your .env to override the key below.
 * Get your key from your CarboniX Dashboard.
 */
const Carbonix = require('carbonix').default;

const cx = new Carbonix({
  apiKey:  process.env.CARBONIX_API_KEY  || '${apiKey}',
  baseUrl: process.env.CARBONIX_BASE_URL || '${baseUrl}',
  timeoutMs: 10_000,
});

module.exports = { cx };
`;

const TELEMETRY_JS_CONTENT = `/**
 * CarboniX Telemetry Reporter
 * Generated by: npx @carbonix/cli init
 * ─────────────────────────────────────────────────────────────────────────────
 * Reports live CPU metrics to your CarboniX Dashboard every 5 minutes.
 * The AI Analyst flags idle/oversized instances and suggests savings.
 */
const os = require('os');
const { cx } = require('./carbonix.config');

function getCpuUtilization() {
  return new Promise(resolve => {
    const t1 = os.cpus();
    setTimeout(() => {
      const t2 = os.cpus();
      let idle = 0, total = 0;
      t1.forEach((cpu, i) => {
        for (const type in t2[i].times) total += t2[i].times[type] - cpu.times[type];
        idle += t2[i].times.idle - cpu.times.idle;
      });
      resolve(parseFloat((1 - idle / total).toFixed(4)));
    }, 100);
  });
}

function startTelemetry({ instanceId, instanceType, provider, region, projectName, intervalMs = 5 * 60 * 1000, storageGb = 0 }) {
  const report = async () => {
    try {
      const cpuUtilization = await getCpuUtilization();
      const record = await cx.ingest({ instanceId, instanceType, provider, region, cpuUtilization, storageGb, projectName });
      console.log(\`[CarboniX] 📊 \${record.carbonKg.toFixed(4)} kg CO₂ | CPU: \${(cpuUtilization * 100).toFixed(1)}% | idle: \${record.isIdle}\`);
    } catch (err) {
      console.warn('[CarboniX] Telemetry failed (non-fatal):', err.message);
    }
  };
  report();
  const timer = setInterval(report, intervalMs);
  if (timer.unref) timer.unref();
  console.log(\`[CarboniX] ✅ Reporting every \${intervalMs / 1000}s for \${instanceId}\`);
  return { stop: () => clearInterval(timer) };
}

module.exports = { startTelemetry };
`;

// ─── Helpers ──────────────────────────────────────────────────────────────────

const ENTRY_FILE_CANDIDATES = [
  'server.js', 'server.ts', 'index.js', 'index.ts', 'app.js', 'app.ts',
  'src/server.js', 'src/server.ts', 'src/index.js', 'src/index.ts',
  'src/app.js', 'src/app.ts', 'main.js', 'main.ts',
];

async function detectEntryFile(cwd: string): Promise<string | null> {
  // 1. Check "main" in package.json first
  try {
    const pkg = JSON.parse(await fs.readFile(path.join(cwd, 'package.json'), 'utf-8'));
    if (pkg.main && await fileExists(path.join(cwd, pkg.main))) return pkg.main;
  } catch (_) {}
  // 2. Walk candidates
  for (const c of ENTRY_FILE_CANDIDATES) {
    if (await fileExists(path.join(cwd, c))) return c;
  }
  return null;
}

async function fileExists(p: string): Promise<boolean> {
  try { await fs.access(p); return true; } catch { return false; }
}

async function detectEnvVars(cwd: string): Promise<Record<string, string>> {
  const vars: Record<string, string> = {};
  try {
    const lines = (await fs.readFile(path.join(cwd, '.env'), 'utf-8')).split('\n');
    for (const line of lines) {
      const m = line.match(/^([^#=]+)=(.*)$/);
      if (m) vars[m[1].trim()] = m[2].trim().replace(/^["']|["']$/g, '');
    }
  } catch (_) {}
  return vars;
}

function buildInjectionSnippet(cfg: Record<string, string>): string {
  return [
    '',
    '// ─── CarboniX Auto-injected by @carbonix/cli (do not remove) ──────────────',
    "const { startTelemetry } = require('./carbonix-telemetry');",
    'startTelemetry({',
    `  instanceId:   process.env.INSTANCE_ID    || '${cfg.instanceId}',`,
    `  instanceType: process.env.INSTANCE_TYPE  || '${cfg.instanceType}',`,
    `  provider:     process.env.CLOUD_PROVIDER || '${cfg.provider}',`,
    `  region:       process.env.AWS_REGION     || '${cfg.region}',`,
    `  projectName:  process.env.APP_NAME       || '${cfg.projectName}',`,
    '});',
    '// ───────────────────────────────────────────────────────────────────────────',
    '',
  ].join('\n');
}

// ─── init command ─────────────────────────────────────────────────────────────

program
  .command('init')
  .description('Initialize CarboniX in your project — scaffolds config, telemetry reporter, and auto-injects tracking')
  .requiredOption('-k, --key <key>', 'Your CarboniX API key (required)')
  .option('--base-url <url>', 'Override the CarboniX API URL', 'http://localhost:4000')
  .action(async (options) => {
    const cwd     = process.cwd();
    const apiKey  = options.key;
    const baseUrl = options.baseUrl;

    console.log('');
    console.log(pc.cyan('🌿 CarboniX — initializing your project...'));
    console.log('');

    // ── Step 1: Verify the API key ──────────────────────────────────────────
    process.stdout.write(pc.gray('  Verifying API key... '));
    try {
      const res = await axios.post(`${baseUrl}/api/v1/carbon/verify-key`, {}, {
        headers: { 'Authorization': `Bearer ${apiKey}` },
      });
      if (!res.data.success) throw new Error('Key invalid');
      console.log(pc.green('✅ Valid'));
    } catch (err: any) {
      console.log(pc.red('❌ Failed'));
      console.error(pc.red(`\n  Error: ${err.response?.data?.error || err.message}`));
      console.error(pc.gray('  Make sure your API key is correct and your CarboniX server is running.'));
      process.exit(1);
    }

    // ── Step 2: Auto-detect provider + region ───────────────────────────────
    const envVars = await detectEnvVars(cwd);
    let provider = 'aws';
    if (process.env.GOOGLE_CLOUD_PROJECT || envVars.GOOGLE_CLOUD_PROJECT) provider = 'gcp';
    if (process.env.ARM_REGION           || envVars.AZURE_REGION)         provider = 'azure';
    if (process.env.VERCEL               || envVars.VERCEL)               provider = 'vercel';
    if (process.env.NETLIFY              || envVars.NETLIFY)              provider = 'netlify';
    if (process.env.RAILWAY_ENVIRONMENT  || envVars.RAILWAY_ENVIRONMENT)  provider = 'railway';
    if (process.env.RENDER               || envVars.RENDER)               provider = 'render';

    const region      = envVars.AWS_REGION || envVars.GCP_REGION || envVars.AZURE_REGION || process.env.AWS_REGION || 'ap-south-1';
    const instanceId  = envVars.INSTANCE_ID   || require('os').hostname();
    const instanceType = envVars.INSTANCE_TYPE || 't3.medium';
    const projectName = envVars.APP_NAME || (() => {
      try { return require(path.join(cwd, 'package.json')).name; } catch { return path.basename(cwd); }
    })();

    const cfg = { instanceId, instanceType, provider, region, projectName };

    // ── Step 3: Write .carbonixrc ────────────────────────────────────────────
    const rcPath = path.join(cwd, '.carbonixrc');
    await fs.writeFile(rcPath, JSON.stringify({ apiKey, provider, region, baseUrl }, null, 2));
    console.log(pc.green('  ✅  Created  .carbonixrc'));

    // ── Step 4: Write carbonix.config.js ────────────────────────────────────
    const configPath = path.join(cwd, 'carbonix.config.js');
    if (!(await fileExists(configPath))) {
      await fs.writeFile(configPath, CONFIG_JS_CONTENT(apiKey, baseUrl));
      console.log(pc.green('  ✅  Created  carbonix.config.js'));
    } else {
      console.log(pc.gray('  ⏭️   Skipped  carbonix.config.js (already exists)'));
    }

    // ── Step 5: Write carbonix-telemetry.js ─────────────────────────────────
    const telemetryPath = path.join(cwd, 'carbonix-telemetry.js');
    if (!(await fileExists(telemetryPath))) {
      await fs.writeFile(telemetryPath, TELEMETRY_JS_CONTENT);
      console.log(pc.green('  ✅  Created  carbonix-telemetry.js'));
    } else {
      console.log(pc.gray('  ⏭️   Skipped  carbonix-telemetry.js (already exists)'));
    }

    // ── Step 6: Auto-inject startTelemetry() ────────────────────────────────
    const entryFile = await detectEntryFile(cwd);
    const MARKER    = 'CarboniX Auto-injected';

    if (entryFile) {
      const entryPath    = path.join(cwd, entryFile);
      const entryContent = await fs.readFile(entryPath, 'utf-8');
      if (entryContent.includes(MARKER)) {
        console.log(pc.gray(`  ⏭️   Skipped  auto-inject (already in ${entryFile})`));
      } else {
        await fs.appendFile(entryPath, buildInjectionSnippet(cfg));
        console.log(pc.green(`  ✅  Injected  startTelemetry() → ${entryFile}`));
        console.log(pc.gray(`              provider: ${provider} | region: ${region}`));
        console.log(pc.gray(`              instanceType: ${instanceType} | project: ${projectName}`));
      }
    } else {
      console.log(pc.yellow('  ⚠️   Entry file not auto-detected. Add this to your server manually:'));
      console.log(pc.gray("       const { startTelemetry } = require('./carbonix-telemetry');"));
      console.log(pc.gray("       startTelemetry({ instanceId: 'my-server', instanceType: 't3.medium', provider: 'aws', region: 'ap-south-1' });"));
    }

    // ── Banner ───────────────────────────────────────────────────────────────
    console.log('');
    console.log(pc.green('╔══════════════════════════════════════════════════════════╗'));
    console.log(pc.green('║       🌿  CarboniX initialized successfully!             ║'));
    console.log(pc.green('╠══════════════════════════════════════════════════════════╣'));
    console.log(pc.green('║                                                          ║'));
    console.log(pc.green(`║  API Key:  ${apiKey.substring(0, 20)}...${' '.repeat(Math.max(0, 27 - apiKey.substring(0, 20).length))}║`));
    console.log(pc.green(`║  Provider: ${provider.padEnd(10)} Region: ${region.padEnd(16)}║`));
    console.log(pc.green('║                                                          ║'));
    console.log(pc.green('║  ✅  .carbonixrc                                        ║'));
    console.log(pc.green('║  ✅  carbonix.config.js                                 ║'));
    console.log(pc.green('║  ✅  carbonix-telemetry.js                              ║'));
    console.log(pc.green('║  ✅  startTelemetry() injected into your entry file     ║'));
    console.log(pc.green('║                                                          ║'));
    console.log(pc.green('║  🚀 Start your server — live data appears on Dashboard! ║'));
    console.log(pc.green('║  Run: carbonix app analyze   — to see AI suggestions    ║'));
    console.log(pc.green('║  Run: carbonix app deploy    — to trigger optimization  ║'));
    console.log(pc.green('║                                                          ║'));
    console.log(pc.green('╚══════════════════════════════════════════════════════════╝'));
    console.log('');
  });


// auth login command
const authCmd = program.command('auth').description('Authentication commands');
authCmd
  .command('login')
  .description('Log into your CarboniX account')
  .action(() => {
    console.log(pc.cyan('\nTo authenticate, please visit your dashboard and generate an API key:'));
    console.log(pc.white('http://localhost:3000/admin/dashboard\n'));
    console.log(pc.gray('Then run: carbonix init --key <your-api-key>\n'));
  });

// app deploy command
const appCmd = program.command('app').description('App management commands');

appCmd
  .command('analyze')
  .description('Analyze local codebase and get Agentic AI region recommendations without deploying')
  .option('-p, --project <project>', 'Target project name')
  .action(async (options) => {
    try {
      // Read config
      let config: any = {};
      try {
        const configData = await fs.readFile(CONFIG_PATH, 'utf-8');
        config = JSON.parse(configData);
      } catch (e) {
        console.error(pc.red('Error: Project not initialized. Run `carbonix init --key <your-api-key>` first.'));
        process.exit(1);
      }

      if (!config.apiKey) {
        console.error(pc.red('Error: API Key not found in .carbonixrc.'));
        process.exit(1);
      }

      console.log(pc.cyan(`\n🔍 CarboniX Agentic AI: Analyzing Local Environment...`));
      
      let currentRegion = config.region || 'us-east-1';
      let currentProvider = config.provider || 'aws';

      const baseTelemetry = {
        projectName: options.project || 'local-analysis',
        instanceType: 't3.medium',
        provider: currentProvider,
        region: currentRegion,
        cpuUtilization: 0.2, // typical baseline
        storageGb: 20
      };

      try {
        const recRes = await axios.post(`${API_URL}/carbon/recommend`, baseTelemetry, {
          headers: {
            'Authorization': `Bearer ${config.apiKey}`,
            'Content-Type': 'application/json'
          }
        });

        if (recRes.data.success) {
          if (recRes.data.data.recommended) {
            const rec = recRes.data.data.recommended;
            console.log(pc.yellow(`\n⚠️  Optimization Found!`));
            console.log(pc.white(`Current Target : ${currentProvider.toUpperCase()} (${currentRegion})`));
            console.log(pc.white(`Current Carbon : ${(rec.co2KgMonth + rec.savingsKg).toFixed(2)} kg CO2e / month`));
            console.log(pc.green(`Recommended    : ${currentProvider.toUpperCase()} (${rec.region})`));
            console.log(pc.green(`New Carbon     : ${rec.co2KgMonth.toFixed(2)} kg CO2e / month`));
            console.log(pc.cyan(`\n✨ Potential Savings: ~${Math.round(rec.reductionPercent)}% carbon reduction (${rec.savingsKg.toFixed(2)} kg)`));
            
            console.log(pc.gray(`\nRun \`carbonix app deploy\` and the Agentic AI will automatically apply this optimization!`));
          } else {
            console.log(pc.green(`\n✓ Your environment is already fully optimized!`));
            console.log(pc.gray(`Current Target : ${currentProvider.toUpperCase()} (${currentRegion})`));
            console.log(pc.gray(`You are running in the greenest available region for your provider.`));
          }
        }
      } catch (e: any) {
        console.error(pc.red(`Error fetching analysis: ${e.message}`));
      }
    } catch (err: any) {
      console.error(pc.red(`Error: ${err.message}`));
    }
  });

appCmd
  .command('deploy')
  .description('Deploy the current codebase and send telemetry to CarboniX')
  .option('-p, --project <project>', 'Target project name')
  .action(async (options) => {
    try {
      // Read config
      let config: any = {};
      try {
        const configData = await fs.readFile(CONFIG_PATH, 'utf-8');
        config = JSON.parse(configData);
      } catch (e) {
        console.error(pc.red('Error: Project not initialized. Run `carbonix init --key <your-api-key>` first.'));
        process.exit(1);
      }

      if (!config.apiKey) {
        console.error(pc.red('Error: API Key not found in .carbonixrc.'));
        process.exit(1);
      }

      // Try to determine project name from package.json
      let projectName = options.project;
      if (!projectName) {
        try {
          const pkgData = await fs.readFile(path.join(process.cwd(), 'package.json'), 'utf-8');
          projectName = JSON.parse(pkgData).name;
        } catch (e) {
          projectName = 'unknown-project';
        }
      }

      console.log(pc.cyan(`\n📦 Packaging codebase for deployment...`));
      
      // Simulate reading telemetry data from the local environment
      let currentRegion = config.region || 'us-east-1';
      let currentProvider = config.provider || 'aws';

      const baseTelemetry = {
        projectName,
        instanceType: 't3.medium', // typical node environment
        provider: currentProvider,
        region: currentRegion,
        cpuUtilization: Math.random() * 0.4 + 0.1, // simulated CPU usage 10-50%
        storageGb: 20
      };

      console.log(pc.cyan(`\n🤖 Agentic AI analyzing deployment plan...`));
      
      try {
        const recRes = await axios.post(`${API_URL}/carbon/recommend`, baseTelemetry, {
          headers: {
            'Authorization': `Bearer ${config.apiKey}`,
            'Content-Type': 'application/json'
          }
        });

        if (recRes.data.success && recRes.data.data.recommended) {
          const rec = recRes.data.data.recommended;
          if (rec.reductionPercent > 10 && rec.region !== currentRegion) {
            console.log(pc.green(`\n✨ Agentic AI Intercepting Deployment ✨`));
            console.log(pc.green(`Switching region from ${currentRegion} to ${rec.region} (within ${currentProvider.toUpperCase()})`));
            console.log(pc.gray(`Expected savings: ~${Math.round(rec.reductionPercent)}% carbon reduction`));
            
            // Rewrite the region internally for telemetry
            currentRegion = rec.region;
            baseTelemetry.region = currentRegion;

            // PAAS INTERCEPTION: Physically rewrite configuration files if they exist
            if (currentProvider.toLowerCase() === 'vercel') {
              try {
                const vercelConfigPath = path.join(process.cwd(), 'vercel.json');
                const vercelData = await fs.readFile(vercelConfigPath, 'utf-8');
                const vercelJson = JSON.parse(vercelData);
                
                // Only rewrite if regions is an array (standard vercel.json format)
                if (vercelJson.regions && Array.isArray(vercelJson.regions)) {
                  vercelJson.regions = [rec.region];
                  await fs.writeFile(vercelConfigPath, JSON.stringify(vercelJson, null, 2));
                  console.log(pc.yellow(`📝 Agentic AI automatically updated vercel.json to use region: ${rec.region}`));
                }
              } catch (err: any) {
                // Ignore if vercel.json doesn't exist or isn't parseable, we just skip file rewriting
                console.log(pc.gray(`(Note: No local vercel.json found to rewrite, skipping file update)`));
              }
            }
          } else {
            console.log(pc.gray(`✓ Deployment plan optimized. Staying in ${currentRegion}.`));
          }
        }
      } catch (e: any) {
        console.log(pc.gray(`Could not fetch AI recommendation, proceeding with default region...`));
      }

      console.log(pc.yellow(`\n☁️  Deploying and uploading telemetry to CarboniX edge (project: ${projectName}, region: ${currentRegion})...`));
      
      const res = await axios.post(`${API_URL}/carbon/telemetry/ingest`, baseTelemetry, {
        headers: {
          'Authorization': `Bearer ${config.apiKey}`,
          'Content-Type': 'application/json'
        }
      });

      if (res.data.success) {
        console.log(pc.green('🚀 Deployment successful!'));
        console.log(pc.gray(`Carbon calculation generated: ${res.data.data.carbonKg.toFixed(2)} kg CO2e`));
      } else {
        console.error(pc.red('Error: Deployment failed.'));
      }
    } catch (err: any) {
      console.error(pc.red(`Error connecting to CarboniX: ${err.response?.data?.error || err.message}`));
    }
  });

// team command
const teamCmd = program.command('team').description('Team management commands');

teamCmd
  .command('sync')
  .description('Automatically discover and sync codebase contributors to CarboniX')
  .action(async () => {
    try {
      let config: any = {};
      try {
        const configData = await fs.readFile(CONFIG_PATH, 'utf-8');
        config = JSON.parse(configData);
      } catch (e) {
        console.error(pc.red('Error: Project not initialized. Run `carbonix init --key <your-api-key>` first.'));
        process.exit(1);
      }

      if (!config.apiKey) {
        console.error(pc.red('Error: API Key not found in .carbonixrc.'));
        process.exit(1);
      }
      
      let projectName = 'unknown-project';
      try {
        const pkgData = await fs.readFile(path.join(process.cwd(), 'package.json'), 'utf-8');
        projectName = JSON.parse(pkgData).name;
      } catch (e) {}

      console.log(pc.cyan(`\n🔍 Analyzing local git history for contributors...`));
      
      const { execSync } = require('child_process');
      let gitOutput = '';
      try {
        gitOutput = execSync('git log --format="%an|%ae" | sort -u', { encoding: 'utf-8' });
      } catch (e) {
        console.log(pc.yellow(`Warning: Not a git repository or git not installed. Could not extract authors.`));
        process.exit(0);
      }

      const rawAuthors = gitOutput.split('\n').filter((l: string) => l.trim() !== '');
      const members = rawAuthors.map((line: string) => {
        const [name, email] = line.split('|');
        return { name, email };
      }).filter((m: any) => {
        const email = m.email?.toLowerCase() || '';
        return m.name && email && !email.includes('dependabot') && !email.includes('bot@');
      });

      if (members.length === 0) {
        console.log(pc.yellow(`No human contributors found.`));
        return;
      }

      console.log(pc.cyan(`Found ${members.length} contributors. Syncing to CarboniX...`));

      const res = await axios.post(`${API_URL}/admin/users/sync`, { members, projectName }, {
        headers: {
          'Authorization': `Bearer ${config.apiKey}`,
          'Content-Type': 'application/json'
        }
      });

      if (res.data.success) {
        console.log(pc.green(`✅ Successfully synced ${res.data.count} team members!`));
        console.log(pc.gray(`Visit your CarboniX dashboard to view their emission ratings.`));
      } else {
        console.error(pc.red('Error: Sync failed.'));
      }
    } catch (err: any) {
      console.error(pc.red(`Error connecting to CarboniX: ${err.response?.data?.error || err.message}`));
    }
  });

program.parse(process.argv);

if (!process.argv.slice(2).length) {
  program.outputHelp();
}
